STEP_LABELS: dict[str, str] = {
    "setup": "环境检查",
    "profile": "数据探查",
    "clean": "数据清洗",
    "plot": "生成分布图",
    "timeseries": "时序分析",
    "tokenize": "文本分词",
    "wordcloud": "生成词云",
    "attribution": "好评归因分析",
    "rating_model": "评分预测模型",
    "funnel": "流量漏斗分析",
    "rfm": "RFM 用户分层",
    "sales": "销量预测与异常",
    "report": "LLM 撰写报告",
    "llm_render_report": "LLM 撰写报告",
    "data_profile": "数据探查",
    "clean_table": "数据清洗",
    "plot_distributions": "生成分布图",
    "eda_timeseries": "时序分析",
    "tokenize_jieba": "文本分词",
    "make_wordcloud": "生成词云",
    "attribution_aspects": "好评归因分析",
    "rating_predict": "评分预测模型",
    "funnel_metrics": "流量漏斗分析",
    "rfm_segment": "RFM 用户分层",
    "sales_forecast": "销量预测与异常",
    "auth": "校验 API 密钥",
    "parse_task": "LLM 理解任务",
    "plan": "LLM 规划步骤",
    "LLM_SCHEMA_MAP": "LLM 识别字段",
    "REACT": "ReAct 边想边做",
    "react": "ReAct 循环",
}
